import type { ThemePalette } from '../api/themes'

type SemanticVariableName = `--color-${string}`

/** Reviewed #16 consumer semantics. Components consume these names; Base24 slots remain projection internals. */
export function projectSemanticConsumerVariables(palette: ThemePalette): Readonly<Record<SemanticVariableName, string>> {
  return {
    '--color-activity-bar-neutral-dark-bg-subtle': reviewedMix(palette.base00, palette.base00, 50),
    '--color-activity-bar-on-strong-text': palette.base07,
    '--color-agent-launch-controls-warning-bg-subtle-alpha-10': reviewedMix(palette.base0A, palette.base00, 10),
    '--color-agent-launch-controls-warning-bg-subtle-alpha-20': reviewedMix(palette.base0A, palette.base00, 20),
    '--color-agent-launch-controls-warning-text': palette.base0A,
    '--color-automation-api-section-neutral-dark-bg-subtle': reviewedMix(palette.base00, palette.base00, 30),
    '--color-automation-runs-section-danger-bg-subtle-alpha-15': reviewedMix(palette.base08, palette.base00, 15),
    '--color-automation-runs-section-danger-bg-subtle-alpha-5': reviewedMix(palette.base08, palette.base00, 5),
    '--color-automation-runs-section-danger-border-subtle': reviewedMix(palette.base08, palette.base00, 30),
    '--color-automation-runs-section-danger-text': palette.base08,
    '--color-automation-runs-section-danger-text-subtle': reviewedMix(palette.base08, palette.base00, 80),
    '--color-automation-runs-section-info-bg-subtle': reviewedMix(palette.base0D, palette.base00, 15),
    '--color-automation-runs-section-info-text': palette.base0D,
    '--color-automation-runs-section-neutral-dark-bg-subtle': reviewedMix(palette.base00, palette.base00, 30),
    '--color-automation-runs-section-success-bg-subtle-alpha-10': reviewedMix(palette.base0B, palette.base00, 10),
    '--color-automation-runs-section-success-bg-subtle-alpha-15': reviewedMix(palette.base0B, palette.base00, 15),
    '--color-automation-runs-section-success-text': palette.base0B,
    '--color-automation-runs-section-warning-bg-subtle': reviewedMix(palette.base0A, palette.base00, 15),
    '--color-automation-runs-section-warning-text': palette.base0A,
    '--color-chat-landing-page-neutral-dark-bg': palette.base00,
    '--color-chat-landing-page-neutral-dark-to': palette.base00,
    '--color-chat-landing-page-on-strong-text': palette.base07,
    '--color-chat-landing-page-warning-bg-subtle': reviewedMix(palette.base0A, palette.base00, 10),
    '--color-chat-landing-page-warning-border-subtle': reviewedMix(palette.base0A, palette.base00, 40),
    '--color-chat-workspace-section-neutral-dark-to': palette.base00,
    '--color-connector-status-page-on-strong-text': palette.base07,
    '--color-connector-status-page-warning-bg': palette.base0A,
    '--color-connector-status-page-warning-bg-subtle': reviewedMix(palette.base0A, palette.base00, 10),
    '--color-connector-status-page-warning-border-subtle': reviewedMix(palette.base0A, palette.base00, 25),
    '--color-connector-status-page-warning-text': palette.base0A,
    '--color-connectors-page-on-strong-text': palette.base07,
    '--color-connectors-page-warning-bg-subtle': reviewedMix(palette.base0A, palette.base00, 5),
    '--color-connectors-page-warning-border-subtle-alpha-25': reviewedMix(palette.base0A, palette.base00, 25),
    '--color-connectors-page-warning-border-subtle-alpha-30': reviewedMix(palette.base0A, palette.base00, 30),
    '--color-connectors-page-warning-text': palette.base0A,
    '--color-credential-modal-neutral-dark-bg-subtle': reviewedMix(palette.base00, palette.base00, 50),
    '--color-credential-modal-warning-bg-subtle': reviewedMix(palette.base0A, palette.base00, 80),
    '--color-credential-modal-warning-text-subtle': reviewedMix(palette.base0A, palette.base00, 90),
    '--color-design-project-page-on-strong-text': palette.base07,
    '--color-design-project-page-warning-bg-subtle': reviewedMix(palette.base0A, palette.base00, 70),
    '--color-dev-page-warning-bg': palette.base0A,
    '--color-first-run-guide-on-strong-text': palette.base07,
    '--color-first-run-guide-warning-text': palette.base0A,
    '--color-html-report-view-muted-color': palette.base04,
    '--color-html-report-view-on-strong-background-color': palette.base07,
    '--color-html-report-view-on-strong-bg': palette.base07,
    '--color-inbox-page-neutral-dark-bg': palette.base00,
    '--color-inbox-reply-thread-neutral-dark-bg': palette.base00,
    '--color-inbox-reply-thread-warning-bg-subtle': reviewedMix(palette.base0A, palette.base00, 10),
    '--color-inbox-reply-thread-warning-text': palette.base0A,
    '--color-inbox-sidebar-neutral-dark-bg': palette.base00,
    '--color-index-info-color': palette.base0D,
    '--color-issue-detail-danger-bg-subtle-alpha-10': reviewedMix(palette.base08, palette.base00, 10),
    '--color-issue-detail-danger-bg-subtle-alpha-15': reviewedMix(palette.base08, palette.base00, 15),
    '--color-issue-detail-danger-border-subtle': reviewedMix(palette.base08, palette.base00, 25),
    '--color-issue-detail-danger-text': palette.base08,
    '--color-issue-detail-info-bg-subtle': reviewedMix(palette.base0D, palette.base00, 15),
    '--color-issue-detail-info-text': palette.base0D,
    '--color-issue-detail-neutral-dark-bg': palette.base00,
    '--color-issue-detail-success-bg-subtle': reviewedMix(palette.base0B, palette.base00, 15),
    '--color-issue-detail-success-text': palette.base0B,
    '--color-issue-detail-warning-bg-subtle-alpha-10': reviewedMix(palette.base0A, palette.base00, 10),
    '--color-issue-detail-warning-bg-subtle-alpha-15': reviewedMix(palette.base0A, palette.base00, 15),
    '--color-issue-detail-warning-border-subtle-alpha-25': reviewedMix(palette.base0A, palette.base00, 25),
    '--color-issue-detail-warning-border-subtle-alpha-30': reviewedMix(palette.base0A, palette.base00, 30),
    '--color-issue-detail-warning-border-subtle-alpha-60': reviewedMix(palette.base0A, palette.base00, 60),
    '--color-issue-detail-warning-text': palette.base0A,
    '--color-issue-status-meta-success-text': palette.base0B,
    '--color-issue-status-meta-warning-text': palette.base0A,
    '--color-issues-board-danger-bg': palette.base08,
    '--color-issues-board-danger-bg-subtle': reviewedMix(palette.base08, palette.base00, 15),
    '--color-issues-board-danger-border-subtle': reviewedMix(palette.base08, palette.base00, 30),
    '--color-issues-board-danger-text': palette.base08,
    '--color-issues-board-danger-text-subtle': reviewedMix(palette.base08, palette.base00, 70),
    '--color-issues-board-info-text': palette.base0D,
    '--color-issues-board-neutral-dark-text': palette.base00,
    '--color-issues-board-success-text-subtle': reviewedMix(palette.base0B, palette.base00, 85),
    '--color-issues-board-warning-bg': palette.base0A,
    '--color-issues-board-warning-bg-subtle-alpha-10': reviewedMix(palette.base0A, palette.base00, 10),
    '--color-issues-board-warning-bg-subtle-alpha-15': reviewedMix(palette.base0A, palette.base00, 15),
    '--color-issues-board-warning-border-subtle': reviewedMix(palette.base0A, palette.base00, 30),
    '--color-issues-board-warning-text': palette.base0A,
    '--color-markdown-what-editor-danger-text': palette.base08,
    '--color-markdown-what-editor-neutral-dark-border': palette.base00,
    '--color-onboarding-design-page-on-strong-text': palette.base07,
    '--color-overview-card-neutral-dark-bg': palette.base00,
    '--color-page-sidebar-layout-neutral-dark-bg': palette.base00,
    '--color-page-sidebar-layout-neutral-dark-bg-subtle': reviewedMix(palette.base00, palette.base00, 40),
    '--color-sdkselector-on-strong-stroke': palette.base07,
    '--color-snapshot-detail-warning-bg': palette.base0A,
    '--color-toggle-on-strong-bg': palette.base07,
    '--color-utadetail-page-on-strong-text': palette.base07,
    '--color-workspace-absorb-panel-neutral-dark-bg': palette.base00,
    '--color-workspace-absorb-panel-on-strong-text': palette.base07,
    '--color-workspace-absorb-panel-warning-bg-subtle-alpha-12': reviewedMix(palette.base0A, palette.base00, 12),
    '--color-workspace-absorb-panel-warning-bg-subtle-alpha-8': reviewedMix(palette.base0A, palette.base00, 8),
    '--color-workspace-absorb-panel-warning-border-subtle': reviewedMix(palette.base0A, palette.base00, 35),
    '--color-workspace-absorb-panel-warning-text': palette.base0A,
    '--color-workspace-aiconfig-modal-neutral-dark-bg-subtle': reviewedMix(palette.base00, palette.base00, 50),
    '--color-workspace-aiconfig-modal-warning-bg-subtle': reviewedMix(palette.base0A, palette.base00, 5),
    '--color-workspace-aiconfig-modal-warning-border-subtle': reviewedMix(palette.base0A, palette.base00, 30),
    '--color-workspace-aiconfig-modal-warning-text-subtle': reviewedMix(palette.base0A, palette.base00, 90),
    '--color-workspace-manager-page-neutral-dark-bg': palette.base00,
    '--color-workspace-manager-page-neutral-dark-to': palette.base00,
    '--color-workspace-manager-page-on-strong-text': palette.base07,
    '--color-workspace-template-upgrade-panel-on-strong-text': palette.base07,
    '--color-workspace-template-upgrade-panel-warning-bg-subtle-alpha-12': reviewedMix(palette.base0A, palette.base00, 12),
    '--color-workspace-template-upgrade-panel-warning-bg-subtle-alpha-8': reviewedMix(palette.base0A, palette.base00, 8),
    '--color-workspace-template-upgrade-panel-warning-border-subtle': reviewedMix(palette.base0A, palette.base00, 35),
    '--color-workspace-template-upgrade-panel-warning-text': palette.base0A,
    '--color-workspaces-danger-background': palette.base08,
    '--color-workspaces-danger-border': palette.base08,
    '--color-workspaces-danger-border-color': palette.base08,
    '--color-workspaces-danger-color': palette.base08,
    '--color-workspaces-neutral-dark-background-subtle-alpha-35': reviewedMix(palette.base00, palette.base00, 35),
    '--color-workspaces-neutral-dark-background-subtle-alpha-55': reviewedMix(palette.base00, palette.base00, 55),
    '--color-workspaces-on-strong-color': palette.base07,
    '--color-workspaces-warning-background': palette.base0A,
  }
}

function reviewedMix(foreground: string, background: string, percentage: number): string {
  return `color-mix(in oklch, ${foreground} ${percentage}%, ${background})`
}

