/**
 * Generate src/migrations/INDEX.md from REGISTRY metadata.
 *
 * Run via: pnpm build:migration-index
 *
 * Wired to the `prebuild` hook so `pnpm build` always regenerates.
 * INDEX.md is committed to the repo — a PR that adds a migration
 * without an INDEX.md update is a visible red flag for reviewers.
 */
import { SUPERVISOR_MIGRATIONS } from '../packages/cli/src/supervisor-default-migration.ts'
import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { MIGRATION_BASELINE, NEXT_MIGRATION_NUMBER, REGISTRY } from '../src/migrations/registry.js'

const here = fileURLToPath(import.meta.url)
const repoRoot = resolve(dirname(here), '..')
const out = resolve(repoRoot, 'src/migrations/INDEX.md')

function escape(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

const rows = REGISTRY.map(m =>
  `| \`${m.id}\` | ${m.appVersion} | ${m.introducedAt} | ${m.affects.join(', ')} | ${escape(m.summary)} |`,
)
const firstActiveMigration = REGISTRY[0]?.id.slice(0, 4)
  ?? String(NEXT_MIGRATION_NUMBER).padStart(4, '0')

const md = `<!-- Auto-generated by scripts/build-migration-index.ts. Do not edit by hand. -->
<!-- Regenerate with \`pnpm build:migration-index\`. -->

# Migration Index

The active migration chain starts after the **${MIGRATION_BASELINE}** baseline.
Development-era migrations before \`${firstActiveMigration}\` are retired and are not runtime-reachable.
Fresh baseline homes are seeded directly from current schemas and defaults.

Each row below corresponds to an active migration in \`src/migrations/\`. The runner applies pending migrations in this order on every boot, recording applied IDs in \`data/config/_meta.json\`.

| ID | App Version | Date | Affects | Summary |
|----|-------------|------|---------|---------|
${rows.length > 0 ? rows.join('\n') : '| _No post-baseline migrations yet_ | — | — | — | — |'}

## Client Supervisor migrations

These run under the Supervisor configuration lock. Their schema version is the
durable idempotency marker; project backends must not apply them through a
project's data/config journal. Existing files remain as backups.

| ID | Schema | Date | Affects | Summary |
|----|--------|------|---------|---------|
${SUPERVISOR_MIGRATIONS.map(m => `| \`${m.id}\` | ${m.schemaVersion} | ${m.introducedAt} | ${m.affects} | ${escape(m.summary)} |`).join('\n')}
`

writeFileSync(out, md)
console.log(`Wrote ${out} (${REGISTRY.length} migrations)`)
