import { writeFile } from 'node:fs/promises'
import { getNewsFeedPresets, newsCollectorSchema, type NewsCollectorConfig } from '../src/domain/news/config.js'

type Feed = NewsCollectorConfig['feeds'][number]
const key = (feed: Feed) => JSON.stringify([feed.source, feed.url, feed.rsshubRoute ?? null])
const defaults = new Map(newsCollectorSchema.parse({}).feeds.map((feed) => [key(feed), feed.enabled]))
const feeds: Feed[] = getNewsFeedPresets()
const cell = (value: string) => value.replaceAll('|', '\\|').replaceAll('\n', ' ')
const rows = feeds.map((feed) => {
  const enabled = defaults.get(key(feed))
  return '| ' + [feed.name, feed.rsshubRoute ? 'RSSHub' : 'RSS / Atom 直连', feed.source, feed.rsshubRoute ?? feed.url, feed.categories?.join(', ') || '—', enabled === undefined ? '按需添加' : enabled ? '初始启用' : '初始停用'].map(cell).join(' | ') + ' |'
}).join('\n')

await writeFile(new URL('../docs/news-sources.md', import.meta.url), `# 新闻源清单

<!-- Generated by scripts/generate-news-sources.ts. Edit the server catalog, then regenerate. -->

供用户和维护者查看内置来源、选择订阅。当前目录共 **${feeds.length} 个来源**，其中 **${feeds.filter((feed) => !feed.rsshubRoute).length} 个直连源**、**${feeds.filter((feed) => feed.rsshubRoute).length} 个 RSSHub 来源**。

这是一张可选来源目录，不是当前用户订阅表，也不是全部来源可用的承诺。新配置初始状态只描述未提供自定义 feeds 时的默认列表；目录中的按需添加项不会自动订阅，生成清单也不会读取或修改用户配置。

## 来源表

| 名称 | 接入方式 | source 标签 | URL / 相对路由 | 分类 | 新配置初始状态 |
|---|---|---|---|---|---|
${rows}

RSSHub 路由使用设置页的共享实例地址；切换实例只影响 RSSHub 来源，不改变普通直连 URL。RSSHub 是用户自行提供、可从 Alice 后端访问的外部服务；OpenAlice 不安装或托管它。

## 使用与兼容

- 在 Settings → News Sources 中显式添加目录项，也可添加或编辑自定义直连源与 RSSHub 路由。查看目录不会改写现有订阅。
- 保存后来源、启停、间隔、共享实例地址与内存策略应用到运行中的单一采集器；在途采集先结束，再使用新配置。减小内存窗口不删除持久归档。
- 旧配置中的完整 URL 保持原样，即使它指向 RSSHub；只有明确设为 RSSHub 相对路由的订阅才跟随共享实例地址。可通过编辑来源、显式选择 RSSHub 类型来转换，不自动迁移或替换订阅。
- 社区非 RSS producer 的导入、可信代码批准、版本选定、订阅及故障重试见[模块设计与操作契约](news-modules/sdd.md)。每个后台独立安装制品，批准锁定内容 hash，不是 OS 沙箱。
- RSSHub 服务 key 通过独立后台接口密封存储；不填入普通 URL 或路由。更换有 key 的实例先清除、改基址、重录。非 loopback 须 HTTPS；源站 Cookie/Token 由 RSSHub 运营者维护。

## 可用性边界

- 清单生成不联网；收录和初始启用均不代表验证通过，公共实例与自建实例的可用性可能不同。
- 当前订阅、启用状态和采集健康度，以 Settings → News Sources 中的用户配置和 Source status 为准。状态与最近成功、失败信息仅保存在进程内，重启后重新采集，不是历史可用性记录。
- 健康记录按订阅 ID（包括旧配置未提供 ID）、source 标签及实际请求 URL 识别；只改名称、分类或采集间隔会保留记录，改变来源身份则重置。无法区分的重复旧订阅在重新配置时重置，不借用另一行的成功记录。
- HTTP 200 不等于健康：响应须具有受支持的 RSS / Atom 外层结构，RSS / RDF 须包含直接子级 channel。合法空 feed 可以成功；这不是完整 XML 或 RFC 合规校验。

## 界面示例

下面是 Demo 模式的设置页：添加来源、编辑相对路由及修改共享实例地址后，直连 URL 保持不变。Demo 不联网采集，手动检查会明确拒绝，不把示例数据标记为已采集成功。

![新闻来源管理设置页（Demo，非实时采集证明）](images/news-source-management-demo.png)


## 维护

[服务端来源目录](../src/domain/news/config.ts)是来源定义的唯一权威入口，也提供设置页的可选来源。新增、删除或修改内置来源后，从仓库根目录运行：

    pnpm exec tsx scripts/generate-news-sources.ts

把生成的表格随目录变更一同维护，不手改本文件的来源行，不另写一份前端预设列表。运行此命令不联网、不启动 collector，不采集新闻。
`)
console.log(`Generated docs/news-sources.md: ${feeds.length} sources`)
