import { describe, expect, it } from 'vitest'
import { validateThemeColorEvidenceManifest } from './evidence.js'
const hash = 'a'.repeat(64), commit = '1'.repeat(40)
const span = { startOffset: 0, endOffset: 4, startLine: 1, startColumn: 1, endLine: 1, endColumn: 5 }
const entry = (overrides: Record<string, unknown> = {}) => ({ kind: 'occurrence-evidence', inventoryId: 'a', source: { path: 'ui/src/A.tsx', sourceText: '#fff', span }, scenario: { scenarioId: 's', state: 'normal', fixtureProfile: 'demo', theme: 'light' }, channel: 'color', actualValue: 'rgb(255, 255, 255)', winner: { kind: 'runtime-value-match', consumedValue: 'rgb(255, 255, 255)' }, target: { active: true, selector: '.a', x: 1, y: 1, width: 10, height: 10 }, sampleBounds: { selector: '.a', x: 1, y: 1, width: 5, height: 5 }, context: { path: 'a-context.png', sha256: hash, width: 100, height: 100, label: 'context' }, crop: { path: 'a-crop.png', sha256: hash, width: 10, height: 10, label: 'occurrence' }, ...overrides })
const run = (entries: unknown[], sourceCommit = commit, ids: string[] = ['a']) => validateThemeColorEvidenceManifest({ schemaVersion: 2, sourceCommit, entries }, ids, commit)
describe('theme color evidence', () => {
  it('accepts exactly one active screenshot entry per occurrence', () => expect(run([entry()]).entries).toHaveLength(1))
  it.each(['scenario-only', 'runtime-value'])('rejects %s records', kind => expect(() => run([entry({ kind })])).toThrow('kind must be occurrence-evidence'))
  it('rejects inactive and stale evidence', () => { expect(() => run([entry({ target: { active: false, selector: '.a', x: 0, y: 0, width: 1, height: 1 } })])).toThrow('inactive'); expect(() => run([], '2'.repeat(40), [])).toThrow('stale') })
  it('rejects orphan, missing, duplicate and plural IDs', () => { expect(() => run([entry({ inventoryId: 'x' })])).toThrow('orphan'); expect(() => run([], commit, ['a'])).toThrow('missing'); expect(() => run([entry(), entry()])).toThrow('shared'); expect(() => run([entry({ inventoryIds: ['a'] })])).toThrow('inventoryIds') })
  it('rejects blank, missing and malformed hashes', () => { for (const sha256 of ['', undefined, 'no']) expect(() => run([entry({ crop: { path: 'x.png', sha256, width: 1, height: 1, label: 'x' } })])).toThrow(/sha256/) })
  it('rejects zero-area targets and stale source metadata', () => { expect(() => run([entry({ target: { active: true, selector: '.a', x: 0, y: 0, width: 0, height: 1 } })])).toThrow('positive area'); expect(() => validateThemeColorEvidenceManifest({ schemaVersion: 2, sourceCommit: commit, entries: [entry()] }, [{ inventoryId: 'a', path: 'ui/src/B.tsx', sourceText: '#fff', span }], commit)).toThrow('stale source') })
  it('requires a structured winner proof', () => { expect(() => run([entry({ winner: undefined })])).toThrow('winner'); expect(run([entry({ winner: { kind: 'tailwind-utility', sourceUtility: 'text-red-400', activeClassToken: 'hover:text-red-400', isolatedValue: 'rgb(1, 2, 3)' } })]).entries[0]?.winner.kind).toBe('tailwind-utility') })
})
