import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { residualReview } from './residual-review-data.js'
import { scenarioInventoryFromReview, validateResidualReview } from './residual-review.js'
import type { RuntimeColorWorklist } from './types.js'

const root = resolve(import.meta.dirname, '../..')
const worklist = JSON.parse(await readFile(resolve(root, '.artifacts/theme-color-audit/runtime-worklist.json'), 'utf8')) as RuntimeColorWorklist
validateResidualReview(worklist, residualReview)
const command = process.argv[2]
if (command === 'validate') console.log(`validated ${residualReview.decisions.length} residual decisions`)
else if (command === 'generate-scenario-inventory') {
  const inventory = scenarioInventoryFromReview(residualReview)
  const output = `// Generated by residual-review-cli.ts. Do not edit; residual-review-data.ts is the source of truth.\nexport const scenarioInventory = ${JSON.stringify(inventory, null, 2)} as const\n`
  await writeFile(resolve(root, 'scripts/theme-color-audit/scenario-inventory.ts'), output)
  console.log(`generated scenario inventory for ${residualReview.decisions.filter((item) => item.disposition.kind !== 'protected-source-data').length} browser targets`)
} else throw new Error(`unknown residual review command: ${command ?? '<missing>'}`)
