import { scenarioInventory as ids } from './scenario-inventory.js'
import type { ThemeColorScenario } from './types.js'

const desktop = { width: 1440, height: 1000 } as const
const mobile = { width: 390, height: 844 } as const
const themes = ['light', 'dark'] as const

export const themeColorScenarios = [
  { scenarioId: 'workspace-overview', route: '/workspaces', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'Workspaces Overview' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: [...ids['workspace-overview'], ...ids['global-css']] },
  { scenarioId: 'workspace-config-dialog', route: '/workspaces', fixtureProfile: 'demo', state: 'dialog-overlay', themes, viewport: desktop, ready: { role: 'heading', name: 'Workspace Settings' }, actions: [{ kind: 'click', role: 'button', name: 'Configure this workspace' }], expectedSurface: 'dom-or-css', inventoryIds: ids['workspace-config-dialog'] },
  { scenarioId: 'workspace-mobile', route: '/workspaces', fixtureProfile: 'demo', state: 'normal', themes, viewport: mobile, ready: { role: 'heading', name: 'Workspaces Overview' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['workspace-mobile'] },
  { scenarioId: 'workspace-terminal', route: '/workspaces/demo-ws', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'main' }, actions: [], expectedSurface: 'typed-non-dom', inventoryIds: ids['workspace-terminal'] },
  { scenarioId: 'first-run', route: '/onboarding', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'main' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['first-run'] },
  { scenarioId: 'chat', route: '/chat', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'What do you want to look into?' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['chat'] },
  { scenarioId: 'automation-runs', route: '/automation/runs', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'Runs' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['automation-runs'] },
  { scenarioId: 'automation-api', route: '/automation/api', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'Workspace automation' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['automation-api'] },
  { scenarioId: 'issues-board', route: '/issues', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'Issues' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['issues-board'] },
  { scenarioId: 'issue-detail', route: '/issues/demo-ws-auto-quant/morning-scan', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'Morning movers scan' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['issue-detail'] },
  { scenarioId: 'trading-as-git', route: '/trading-as-git', fixtureProfile: 'demo', state: 'warning', stateDriver: 'fixture', themes, viewport: desktop, ready: { role: 'heading', name: 'Trading as Git' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['trading-as-git'] },
  { scenarioId: 'market-detail', route: '/market/equity/AAPL', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'AAPL' }, actions: [], expectedSurface: 'typed-non-dom', inventoryIds: ids['market-detail'] },
  { scenarioId: 'market-board', route: '/market/boards/sp500', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'main' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['market-board'] },
  { scenarioId: 'market-rotation', route: '/market/rotation', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'main' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['market-rotation'] },
  { scenarioId: 'connector-status', route: '/connectors', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'Connectors' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['connector-status'] },
  { scenarioId: 'connector-settings', route: '/settings/connectors', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'Connectors' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['connector-settings'] },
  { scenarioId: 'ai-credential-dialog', route: '/settings/ai-provider', fixtureProfile: 'demo', state: 'dialog-overlay', themes, viewport: desktop, ready: { role: 'heading', name: 'Add credential' }, actions: [{ kind: 'click', role: 'button', name: '+ Add' }], expectedSurface: 'dom-or-css', inventoryIds: ids['ai-credential-dialog'] },
  { scenarioId: 'inbox', route: '/inbox', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'Inbox' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['inbox'] },
  { scenarioId: 'portfolio', route: '/portfolio', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'Portfolio' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['portfolio'] },
  { scenarioId: 'trading-settings', route: '/settings/trading', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'Trading' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['trading-settings'] },
  { scenarioId: 'create-uta-dialog', route: '/settings/trading', fixtureProfile: 'demo', state: 'dialog-overlay', themes, viewport: desktop, ready: { role: 'heading', name: 'Connect Broker · Pick Platform' }, actions: [{ kind: 'click', role: 'button', name: '+ Add UTA' }], expectedSurface: 'dom-or-css', inventoryIds: ids['create-uta-dialog'] },
  { scenarioId: 'uta-detail', route: '/settings/uta/demo-ibkr', fixtureProfile: 'demo', state: 'dialog-overlay', themes, viewport: desktop, ready: { role: 'heading', name: 'Place Order' }, actions: [{ kind: 'click', role: 'button', name: '+ Place Order' }], expectedSurface: 'dom-or-css', inventoryIds: ids['uta-detail'] },
  { scenarioId: 'agent-permissions', route: '/settings/agent-permissions', fixtureProfile: 'demo', state: 'disabled', stateDriver: 'fixture', themes, viewport: desktop, ready: { role: 'heading', name: 'Agent Permissions' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['agent-permissions'] },
  { scenarioId: 'simulator', route: '/dev/simulator', fixtureProfile: 'demo', state: 'error', stateDriver: 'route', themes, viewport: desktop, ready: { role: 'heading', name: 'Simulator' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['simulator'] },
  { scenarioId: 'onboarding-design', route: '/design/first-run-onboarding', fixtureProfile: 'demo', state: 'normal', themes, viewport: desktop, ready: { role: 'heading', name: 'First-run onboarding' }, actions: [], expectedSurface: 'dom-or-css', inventoryIds: ids['onboarding-design'] },
] as const satisfies readonly ThemeColorScenario[]
