// Generated by residual-review-cli.ts. Do not edit; residual-review-data.ts is the source of truth.
export const scenarioInventory = {
  "agent-permissions": [],
  "ai-credential-dialog": [],
  "automation-api": [],
  "automation-runs": [],
  "chat": [],
  "connector-settings": [],
  "connector-status": [],
  "create-uta-dialog": [
    "color-3a44ec475306c0e9d3d7"
  ],
  "first-run": [],
  "global-css": [
    "color-a1a26f258a7fbbdbe131",
    "color-d7d58e4dfbb3028fa1fb",
    "color-2bb33a2ca9e54c5a28d1",
    "color-da57229f25c270008370",
    "color-6697e3270ecda8da085f",
    "color-65fad81f1a4eec83881d",
    "color-a4accdd1e833c1e516c8",
    "color-36aead8fa2e0e54a33ed",
    "color-7c934a658d62469a1862",
    "color-5445b5f7fe99cc0f8707",
    "color-2833fbb9d0848ce47509",
    "color-dc5086eee0bb39e03b48"
  ],
  "inbox": [],
  "issue-detail": [],
  "issues-board": [],
  "market-board": [],
  "market-detail": [
    "color-5342a2ec7be48dcf0bc8",
    "color-c0d7545df9514efb606f",
    "color-92b88e6d693ce872d05f",
    "color-6e486fc82329de0722b3"
  ],
  "market-rotation": [],
  "onboarding-design": [],
  "portfolio": [],
  "simulator": [
    "color-ed404f80a0d816f47659"
  ],
  "trading-as-git": [
    "color-fc39f0c208f8c60877f5"
  ],
  "trading-settings": [],
  "uta-detail": [],
  "workspace-config-dialog": [],
  "workspace-mobile": [],
  "workspace-overview": [],
  "workspace-terminal": [
    "color-c2ede41d725f6ffeb91c",
    "color-9ed31ee430992d65b2d4",
    "color-dbe0d64d1bfcfdde51f9",
    "color-b11a84070c5b31870cf9",
    "color-3bf871aa30ef2daa9c4f",
    "color-ee2a601683fe8af57fc0",
    "color-700feacb3627b8b8aac4",
    "color-feb7653bad6501870cb0",
    "color-e539e4da5c5fcaa79e15",
    "color-1ce410d7e37f382a9d36",
    "color-33f50e0e713f740dc7de",
    "color-831c90547409921b1911",
    "color-b9598f01b8a9a87c3a8b",
    "color-b079cd359c85a1184062",
    "color-690cecd6eaf1a4cf3fb8",
    "color-9f704b33c9fe8e2d44c0",
    "color-4513f66238d75149ec7e",
    "color-36c1561a3f1a8820af8f",
    "color-e848f9c740205ec6720a",
    "color-003d5fbf6d5b24c1611c",
    "color-1e1ee7c13829c01b1dcf",
    "color-a3aa4d22a4a9fe8f9f87",
    "color-21dd6b1a08f483e99e1c",
    "color-decb08654a737e36ec6c",
    "color-449797a792f8937e54b1",
    "color-bdedd90ca9146f43dfff",
    "color-1aaa13b52b7bd57b9e02",
    "color-6bf0b8a3c37ccfd516b0",
    "color-ee220623240d97426c5d"
  ]
} as const
