import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defaultProcessController } from '@traderalice/guardian-runtime'
import { NewsWorkerHost } from './host.js'
import type { NewsSubscription } from './contract.js'

const hash = 'a'.repeat(64)
const launch = { command: process.env.OPENALICE_NEWS_TEST_NODE ?? process.execPath, args: ['--conditions=openalice-source', '--import', import.meta.resolve('tsx'), fileURLToPath(new URL('./worker-entry.ts', import.meta.url))] }
const row: NewsSubscription = { id: 'one', moduleId: 'test.news', sourceKey: 'latest', name: 'News', source: 'test', enabled: true, params: {}, categories: [] }
const item = { externalId: 'article-1', title: 'News', content: 'Real worker', url: 'https://example.test/article', publishedAt: '2026-01-01T00:00:00Z' }
let home: string
let hosts: NewsWorkerHost[]

beforeEach(async () => { home = await mkdtemp(join(tmpdir(), 'openalice-news-host-')); hosts = [] })
afterEach(async () => {
  try { for (const host of hosts) await host.stop() }
  finally { await rm(home, { recursive: true, force: true }) }
})
async function start(code: string): Promise<NewsWorkerHost> {
  const entry = join(home, 'entry.mjs')
  await writeFile(entry, code)
  const host = new NewsWorkerHost(home, hash, launch)
  hosts.push(host)
  await host.start(entry, 'test.news', '1')
  return host
}
const moduleCode = (body: string) => 'export const newsModule = { abiVersion: 1, moduleId: "test.news", version: "1", async collect(input) { ' + body + ' } }'

describe('real news module worker process', () => {
  it('loads an actual .mjs and exchanges a typed collection batch with the child', async () => {
    const host = await start(moduleCode('return [{ ...' + JSON.stringify(item) + ', title: input.sourceKey }]'))
    expect(host.isLoaded()).toBe(true)
    expect(await host.collect(row)).toEqual([{ ...item, title: 'latest' }])
  }, 30_000)

  it.each([
    ['wrong ABI', 'export const newsModule = { abiVersion: 2, moduleId: "test.news", version: "1", collect: async () => [] }'],
    ['missing export', 'export const otherModule = { abiVersion: 1 }'],
    ['missing dependency', 'import "./missing.mjs"; export const newsModule = {}'],
  ])('rejects %s at startup rather than loading the worker', async (_name, code) => {
    await expect(start(code)).rejects.toThrow()
    expect(hosts[0]?.isLoaded()).toBe(false)
  }, 30_000)

  it('rejects a bad batch generated by the actual module', async () => {
    const host = await start(moduleCode('return [{ ...' + JSON.stringify(item) + ', url: "file:///secret" }]'))
    await expect(host.collect(row)).rejects.toThrow()
    expect(host.isLoaded()).toBe(false)
  }, 30_000)

  it('isolates an abrupt child crash and refuses another collection', async () => {
    const host = await start(moduleCode('process.exit(23)'))
    await expect(host.collect(row)).rejects.toThrow()
    await expect(host.collect(row)).rejects.toThrow()
    expect(host.isLoaded()).toBe(false)
  }, 30_000)

  it('times out a hung collect and marks the worker unavailable', async () => {
    const host = await start(moduleCode('return new Promise(() => {})'))
    await expect(host.collect(row)).rejects.toThrow()
    expect(host.isLoaded()).toBe(false)
  }, 35_000)

  it('stops a real child and its spawned descendant, not only the direct worker', async () => {
    const pidFile = join(home, 'descendant.pid')
    const code = 'import { spawn } from "node:child_process"; import { writeFileSync } from "node:fs"; ' +
      'const child = spawn(process.execPath, ["-e", "setInterval(() => {}, 1000)"], { stdio: "ignore" }); ' +
      'writeFileSync(' + JSON.stringify(pidFile) + ', String(child.pid)); ' + moduleCode('return []')
    const host = await start(code)
    const pid = Number(await readFile(pidFile, 'utf8'))
    expect(pid).toBeGreaterThan(0)
    expect(defaultProcessController.isAlive(pid)).toBe(true)
    await host.stop()
    await expect.poll(() => defaultProcessController.isAlive(pid), { timeout: 5000, interval: 100 }).toBe(false)
  }, 35_000)

  it.skipIf(process.platform === 'win32')('stops a detached descendant before the supervisor exits', async () => {
    const pidFile = join(home, 'detached-descendant.pid')
    const code = 'import { spawn } from "node:child_process"; import { writeFileSync } from "node:fs"; ' +
      'const child = spawn(process.execPath, ["-e", "setInterval(() => {}, 1000)"], { stdio: "ignore", detached: true }); ' +
      'writeFileSync(' + JSON.stringify(pidFile) + ', String(child.pid)); ' + moduleCode('return []')
    const host = await start(code)
    const pid = Number(await readFile(pidFile, 'utf8'))
    expect(pid).toBeGreaterThan(0)
    expect(defaultProcessController.isAlive(pid)).toBe(true)
    await host.stop()
    await expect.poll(() => defaultProcessController.isAlive(pid), { timeout: 5000, interval: 100 }).toBe(false)
  }, 35_000)
})
